#!/usr/bin/python
# -*- coding: utf-8 -*-

# wscript in ./test/matrix2020

import os

def build(bld):
    print('→ build from ' + bld.path.abspath())
    
    # detect files that should be build
    for file in os.listdir( bld.path.abspath() ):
        if file.endswith(".cpp"):
            # print(" _should build "+file[:-4])
            bld.program(
                source=[file],
                target = file[:-4],
                includes=['.', '../../include', '../../src'],
                libs = ['m'],
                use = [ 'matrix2020_objs', 'SOIL', 'STB','PA',
                       'VORBIS','FTGL','OPENGL','GLFW3',
                       'FREETYPE2','BOOST'
                ]
            )
