#!/usr/bin/env python
# encoding: utf-8

# wscript in ./test

import os

def build(bld):
    print('→ build from ' + bld.path.abspath())
    
    # detect files that should be build
    for file in os.listdir( bld.path.abspath() ):
        if file.endswith(".cpp"):
            if not file.startswith( "test-2" ):
                print(" _should build "+file[:-4])
                bld.program(
                    source=[file],
                    target = file[:-4],
                    includes=['.', '../include', '../src'],
                    libs = ['m'],
                    use = ['chuchu_objs','SOIL','PA',
                           'VORBIS','FTGL','OPENGL','GLFW3',
                           'FREETYPE2','BOOST'
                    ]
                )
            else:
                print(" _should build with LUA "+file[:-4])
                bld.program(
                    source=[file],
                    target = file[:-4],
                    includes=['.', '../include', '../src'],
                    libs = ['m'],
                    use = [ 'LUA53',
                    ]
                )

        
    
    
# =======
# def build(bld):
#     bld.program(
#         source=['test-013-gltext.cpp'], target='test-013-gltext',
#         includes=['.','../src',],
#         libs=['m'],
#         use = ['OPENGL','GLFW3','FREETYPE2']
#     )
# >>>>>>> text
