#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(
        source=['test-013-gltext.cpp'], target='test-013-gltext',
        includes=['.','../src',],
        libs=['m'],
        use = ['OPENGL','GLFW3','FREETYPE2']
    )
