#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(
        source=['tactiship.cpp', 'trackball.cc'], target='tactiship',
        includes=['.','..'],
        libs=['m'],
        use = ['OPENGL','GLFW3']
    )
    bld.program(
        source=['simulator.cpp', 'trackball.cc'], target='simulator',
        includes=['.','..'],
        libs=['m'],
        use = ['OPENGL','GLFW3']
    )
