#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(
        source=['test_tree.cpp'],
        target='test_tree',
        includes=['.'],
        libs=['m'],
        use=['']
    )
    bld.program(
        source=['test_ttt.cpp'],
        target='test_ttt',
        includes=['.'],
        libs=['m'],
        use=['']
    )

