#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(
        source=['test_core.cpp'], target='test_core',
        includes=['.','..'],
        libs=['m'],
        use = []
    )
