#!/usr/bin/python
# -*- coding: utf-8 -*-

# wscript in ./src

import os

def build( bld ):
    print('→ build from ' + bld.path.abspath())

    ## List of *.cpp files to add to chuchu_objs
    l_chuchu = []
    for file in os.listdir( bld.path.abspath() ):
        if file.endswith(".cpp"):
            l_chuchu.append( file )

    bld.objects(
        source  = l_chuchu,
        includes = ['.','../include'],
        target  = 'chuchu_objs')

    # link: create bld link to 'shader'
    def link_data(bld):
        # link if not exists already
        if not os.access(  bld.bldnode.abspath()+'/src/shaders', os.F_OK ) :
            print( "link source",bld.srcnode.abspath()+'/src/shaders' )
            print( "link name",bld.bldnode.abspath()+'/src/shaders' )
            os.symlink( bld.srcnode.abspath()+'/src/shaders',
                     bld.bldnode.abspath()+'/src/shaders' )

    ## WARN when waf clean, also clean shaders !!!
    ##bld.add_post_fun( link_data )


